//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_work4
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_InfoSclad
    {
        public int Number_of_contract { get; set; }
        public Nullable<System.DateTime> Date_of_contract { get; set; }
        public string Terms_of_an_agreement { get; set; }
        public string Name { get; set; }
        public string Account_number { get; set; }
        public string NameCustomer { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Date_of_receiving { get; set; }
        public Nullable<int> Number_of_sclad { get; set; }
        public string NameProduct { get; set; }
        public string Container { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Quality_certificate { get; set; }
        public double Price { get; set; }
        public Nullable<int> Quntity_products { get; set; }
        public string NameSuplier { get; set; }
        public string AddressSupplier { get; set; }
        public string PhoneSupplier { get; set; }
        public Nullable<System.DateTime> Shipping_date { get; set; }
    }
}
